# http://eslint.org/docs/rules/

root: true
env:
  node: true
plugins:
  - prettier
extends:
  - eslint:recommended
  - prettier
rules:
  prettier/prettier:
    - 2
    - singleQuote: true
  no-console: 1
