version: 2
jobs:
  build:
    working_directory: ~/herman
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: herman-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Set $PATH
          command: echo 'export PATH=~/herman/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Check that yarn.lock matches package.json
          command: |
            if [[ ! "${CIRCLE_BRANCH}" =~ greenkeeper\/.* ]]; then
              [[ $(git diff --name-only yarn.lock) == "" ]] && exit 0
              echo ">> yarn.lock is out of date, run \"yarn\""
              exit 1
            fi
      - run:
          name: Install NVM
          command: wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
      - save_cache:
          key: herman-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "~/.cache/yarn"
            - "~/.nvm"
      - run:
          name: Lint JS
          command: gulp eslint
      - run:
          name: Lint Sass
          command: gulp sasslint
      - run:
          name: Test Sass
          command: gulp sasstest
      - run:
          name: Run JS Tests [node latest]
          command: |
            gulp jstest
            nyc check-coverage --statements=100 --functions=100 --branches=100 --lines=100
            nyc report --reporter=text-lcov | coveralls
      - run:
          name: Run Client JS Tests & Check Coverage
          command: |
            gulp clienttest-check-coverage
            nyc report --reporter=text-lcov --temp-directory ./jscov/client/ | coveralls
      - run:
          name: Run JS Tests [node 6]
          command: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install 6.2.2
            yarn install --force
            gulp jstest
            nyc check-coverage --statements=100 --functions=100 --branches=100 --lines=100
      - deploy:
          name: Update yarn.lock [greenkeeper]
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ greenkeeper\/.* ]]; then
              yarn global add greenkeeper-lockfile@1 --prefix ~/.yarn
              ~/.yarn/bin/greenkeeper-lockfile-update
              ~/.yarn/bin/greenkeeper-lockfile-upload
            fi
      - store_artifacts:
          path: jscov
          destination: js-reports
      - store_test_results:
          path: jscov
